<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ead808c8e5a4',
	'title' => 'COVID19 POPUP',
	'fields' => array(
		array(
			'key' => 'field_5eae72e9cf037',
			'label' => 'Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ead80a8ad800',
			'label' => 'Add to whole site',
			'name' => 'add_to_whole_site',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ead8112ad801',
			'label' => 'Select Country',
			'name' => 'select_country',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Global' => 'All Countries',
				'ala-aland-islands' => 'ALA Aland Islands',
				'afghanistan' => 'Afghanistan',
				'albania' => 'Albania',
				'algeria' => 'Algeria',
				'american-samoa' => 'American Samoa',
				'andorra' => 'Andorra',
				'angola' => 'Angola',
				'anguilla' => 'Anguilla',
				'antarctica' => 'Antarctica',
				'antigua-and-barbuda' => 'Antigua and Barbuda',
				'argentina' => 'Argentina',
				'armenia' => 'Armenia',
				'aruba' => 'Aruba',
				'australia' => 'Australia',
				'austria' => 'Austria',
				'azerbaijan' => 'Azerbaijan',
				'bahamas' => 'Bahamas',
				'bahrain' => 'Bahrain',
				'bangladesh' => 'Bangladesh',
				'barbados' => 'Barbados',
				'belarus' => 'Belarus',
				'belgium' => 'Belgium',
				'belize' => 'Belize',
				'benin' => 'Benin',
				'bermuda' => 'Bermuda',
				'bhutan' => 'Bhutan',
				'bolivia' => 'Bolivia',
				'bosnia-and-herzegovina' => 'Bosnia and Herzegovina',
				'botswana' => 'Botswana',
				'bouvet-island' => 'Bouvet Island',
				'brazil' => 'Brazil',
				'british-indian-ocean-territory' => 'British Indian Ocean Territory',
				'british-virgin-islands' => 'British Virgin Islands',
				'brunei' => 'Brunei Darussalam',
				'bulgaria' => 'Bulgaria',
				'burkina-faso' => 'Burkina Faso',
				'burundi' => 'Burundi',
				'cambodia' => 'Cambodia',
				'cameroon' => 'Cameroon',
				'canada' => 'Canada',
				'cape-verde' => 'Cape Verde',
				'cayman-islands' => 'Cayman Islands',
				'central-african-republic' => 'Central African Republic',
				'chad' => 'Chad',
				'chile' => 'Chile',
				'china' => 'China',
				'christmas-island' => 'Christmas Island',
				'cocos-keeling-islands' => 'Cocos (Keeling) Islands',
				'colombia' => 'Colombia',
				'comoros' => 'Comoros',
				'congo-brazzaville' => 'Congo (Brazzaville)',
				'congo-kinshasa' => 'Congo (Kinshasa)',
				'cook-islands' => 'Cook Islands',
				'costa-rica' => 'Costa Rica',
				'croatia' => 'Croatia',
				'cuba' => 'Cuba',
				'cyprus' => 'Cyprus',
				'czech-republic' => 'Czech Republic',
				'cote-divoire' => 'Côte d\'Ivoire',
				'denmark' => 'Denmark',
				'djibouti' => 'Djibouti',
				'dominica' => 'Dominica',
				'dominican-republic' => 'Dominican Republic',
				'ecuador' => 'Ecuador',
				'egypt' => 'Egypt',
				'el-salvador' => 'El Salvador',
				'equatorial-guinea' => 'Equatorial Guinea',
				'eritrea' => 'Eritrea',
				'estonia' => 'Estonia',
				'ethiopia' => 'Ethiopia',
				'falkland-islands-malvinas' => 'Falkland Islands (Malvinas)',
				'faroe-islands' => 'Faroe Islands',
				'fiji' => 'Fiji',
				'finland' => 'Finland',
				'french-guiana' => 'French Guiana',
				'french-polynesia' => 'French Polynesia',
				'french-southern-territories' => 'French Southern Territories',
				'gabon' => 'Gabon',
				'gambia' => 'Gambia',
				'georgia' => 'Georgia',
				'germany' => 'Germany',
				'ghana' => 'Ghana',
				'gibraltar' => 'Gibraltar',
				'greece' => 'Greece',
				'greenland' => 'Greenland',
				'grenada' => 'Grenada',
				'guadeloupe' => 'Guadeloupe',
				'guam' => 'Guam',
				'guatemala' => 'Guatemala',
				'guernsey' => 'Guernsey',
				'guinea' => 'Guinea',
				'guinea-bissau' => 'Guinea-Bissau',
				'guyana' => 'Guyana',
				'haiti' => 'Haiti',
				'heard-and-mcdonald-islands' => 'Heard and Mcdonald Islands',
				'holy-see-vatican-city-state' => 'Holy See (Vatican City State)',
				'honduras' => 'Honduras',
				'hong-kong-sar-china' => 'Hong Kong, SAR China',
				'hungary' => 'Hungary',
				'iceland' => 'Iceland',
				'india' => 'India',
				'indonesia' => 'Indonesia',
				'iran' => 'Iran, Islamic Republic of',
				'iraq' => 'Iraq',
				'ireland' => 'Ireland',
				'isle-of-man' => 'Isle of Man',
				'israel' => 'Israel',
				'italy' => 'Italy',
				'jamaica' => 'Jamaica',
				'japan' => 'Japan',
				'jersey' => 'Jersey',
				'jordan' => 'Jordan',
				'kazakhstan' => 'Kazakhstan',
				'kenya' => 'Kenya',
				'kiribati' => 'Kiribati',
				'korea-north' => 'Korea (North)',
				'korea-south' => 'Korea (South)',
				'kuwait' => 'Kuwait',
				'kyrgyzstan' => 'Kyrgyzstan',
				'lao-pdr' => 'Lao PDR',
				'latvia' => 'Latvia',
				'lebanon' => 'Lebanon',
				'lesotho' => 'Lesotho',
				'liberia' => 'Liberia',
				'libya' => 'Libya',
				'liechtenstein' => 'Liechtenstein',
				'lithuania' => 'Lithuania',
				'luxembourg' => 'Luxembourg',
				'macao-sar-china' => 'Macao, SAR China',
				'macedonia' => 'Macedonia, Republic of',
				'madagascar' => 'Madagascar',
				'malawi' => 'Malawi',
				'malaysia' => 'Malaysia',
				'maldives' => 'Maldives',
				'mali' => 'Mali',
				'marshall-islands' => 'Marshall Islands',
				'martinique' => 'Martinique',
				'mauritania' => 'Mauritania',
				'mauritius' => 'Mauritius',
				'mayotte' => 'Mayotte',
				'mexico' => 'Mexico',
				'micronesia' => 'Micronesia, Federated States of',
				'moldova' => 'Moldova',
				'monaco' => 'Monaco',
				'mongolia' => 'Mongolia',
				'montenegro' => 'Montenegro',
				'montserrat' => 'Montserrat',
				'morocco' => 'Morocco',
				'mozambique' => 'Mozambique',
				'myanmar' => 'Myanmar',
				'namibia' => 'Namibia',
				'nauru' => 'Nauru',
				'nepal' => 'Nepal',
				'netherlands' => 'Netherlands',
				'netherlands-antilles' => 'Netherlands Antilles',
				'new-caledonia' => 'New Caledonia',
				'new-zealand' => 'New Zealand',
				'nicaragua' => 'Nicaragua',
				'niger' => 'Niger',
				'nigeria' => 'Nigeria',
				'niue' => 'Niue',
				'norfolk-island' => 'Norfolk Island',
				'northern-mariana-islands' => 'Northern Mariana Islands',
				'norway' => 'Norway',
				'oman' => 'Oman',
				'pakistan' => 'Pakistan',
				'palau' => 'Palau',
				'palestine' => 'Palestinian Territory',
				'panama' => 'Panama',
				'papua-new-guinea' => 'Papua New Guinea',
				'paraguay' => 'Paraguay',
				'peru' => 'Peru',
				'philippines' => 'Philippines',
				'pitcairn' => 'Pitcairn',
				'poland' => 'Poland',
				'puerto-rico' => 'Puerto Rico',
				'qatar' => 'Qatar',
				'kosovo' => 'Republic of Kosovo',
				'romania' => 'Romania',
				'russia' => 'Russian Federation',
				'rwanda' => 'Rwanda',
				'réunion' => 'Réunion',
				'saint-helena' => 'Saint Helena',
				'saint-kitts-and-nevis' => 'Saint Kitts and Nevis',
				'saint-lucia' => 'Saint Lucia',
				'saint-pierre-and-miquelon' => 'Saint Pierre and Miquelon',
				'saint-vincent-and-the-grenadines' => 'Saint Vincent and Grenadines',
				'saint-barthélemy' => 'Saint-Barthélemy',
				'saint-martin-french-part' => 'Saint-Martin (French part)',
				'samoa' => 'Samoa',
				'san-marino' => 'San Marino',
				'sao-tome-and-principe' => 'Sao Tome and Principe',
				'saudi-arabia' => 'Saudi Arabia',
				'senegal' => 'Senegal',
				'serbia' => 'Serbia',
				'seychelles' => 'Seychelles',
				'sierra-leone' => 'Sierra Leone',
				'singapore' => 'Singapore',
				'slovakia' => 'Slovakia',
				'slovenia' => 'Slovenia',
				'solomon-islands' => 'Solomon Islands',
				'somalia' => 'Somalia',
				'south-africa' => 'South Africa',
				'south-georgia-and-the-south-sandwich-islands' => 'South Georgia and the South Sandwich Islands',
				'south-sudan' => 'South Sudan',
				'spain' => 'Spain',
				'sri-lanka' => 'Sri Lanka',
				'sudan' => 'Sudan',
				'suriname' => 'Suriname',
				'svalbard-and-jan-mayen-islands' => 'Svalbard and Jan Mayen Islands',
				'swaziland' => 'Swaziland',
				'sweden' => 'Sweden',
				'switzerland' => 'Switzerland',
				'syria' => 'Syrian Arab Republic (Syria)',
				'taiwan' => 'Taiwan, Republic of China',
				'tajikistan' => 'Tajikistan',
				'tanzania' => 'Tanzania, United Republic of',
				'thailand' => 'Thailand',
				'timor-leste' => 'Timor-Leste',
				'togo' => 'Togo',
				'tokelau' => 'Tokelau',
				'tonga' => 'Tonga',
				'trinidad-and-tobago' => 'Trinidad and Tobago',
				'tunisia' => 'Tunisia',
				'turkey' => 'Turkey',
				'turkmenistan' => 'Turkmenistan',
				'turks-and-caicos-islands' => 'Turks and Caicos Islands',
				'tuvalu' => 'Tuvalu',
				'us-minor-outlying-islands' => 'US Minor Outlying Islands',
				'uganda' => 'Uganda',
				'ukraine' => 'Ukraine',
				'united-arab-emirates' => 'United Arab Emirates',
				'united-kingdom' => 'United Kingdom',
				'united-states' => 'United States of America',
				'uruguay' => 'Uruguay',
				'uzbekistan' => 'Uzbekistan',
				'vanuatu' => 'Vanuatu',
				'venezuela' => 'Venezuela (Bolivarian Republic)',
				'vietnam' => 'Viet Nam',
				'virgin-islands' => 'Virgin Islands, US',
				'wallis-and-futuna-islands' => 'Wallis and Futuna Islands',
				'western-sahara' => 'Western Sahara',
				'yemen' => 'Yemen',
				'zambia' => 'Zambia',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ead8143ad802',
			'label' => 'All Countries Data',
			'name' => 'all_countries_data',
			'type' => 'true_false',
			'instructions' => '<b>Note:</b> Just check this and display Global and your selected Country both data.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_5eae72f2cf038',
			'label' => 'Appearance',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5eae730dcf039',
			'label' => 'Header',
			'name' => 'header',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5eae731fcf03a',
					'label' => 'Background Color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5eae7340cf03c',
					'label' => 'Text Color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
			),
		),
		array(
			'key' => 'field_5eae7350cf03d',
			'label' => 'Body',
			'name' => 'body',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5eae7350cf03e',
					'label' => 'Background Color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5eae7350cf03f',
					'label' => 'Text Color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
			),
		),
		array(
			'key' => 'field_5ee2f914650ed',
			'label' => 'Layouts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ee2f922650ee',
			'label' => 'Choose Layout',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<b>Layouts</b> will be coming soon with the <b>PREMIUM</b> version. Let me know in forum if you have any suggestions or advice.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
?>